'use strict';
const DATA=window.HANTALK_DATA;
const KEY='hantalk_v7_state';
const defaultState={itinerary:DATA.itinerary,expenses:[],favorites:[],krwPerTwd:42.5};
let state=load();let currentCategory='全部';let modalPhrase=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function openModal(id){const el=document.getElementById(id);el.classList.add('show');el.setAttribute('aria-hidden','false')}
function closeModal(id){const el=document.getElementById(id);el.classList.remove('show');el.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));

document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+btn.dataset.page));scrollTo({top:0,behavior:'smooth'})}));

function renderPlan(){const root=document.getElementById('planList');root.innerHTML=state.itinerary.map((d,di)=>`<article class="card"><div class="day-head"><div><div class="day-title">${esc(d.day)}｜${esc(d.title)}</div><div class="day-date">${esc(d.date)}・${esc(d.summary||'')}</div></div><button class="btn mini edit-day" data-index="${di}">編輯</button></div><div class="timeline">${d.items.map((x,ii)=>`<div class="stop"><div class="stop-time">${esc(x[0])}</div><div class="stop-place">${esc(x[1])}<span class="stop-kind">${esc(x[2])}</span><div class="actions"><a class="btn mini" target="_blank" rel="noopener" href="https://map.naver.com/p/search/${encodeURIComponent(x[1])}">📍 導航</a></div></div></div>`).join('')}</div></article>`).join('')||'<div class="empty">尚無行程</div>';document.querySelectorAll('.edit-day').forEach(b=>b.addEventListener('click',()=>openDayForm(Number(b.dataset.index))))}
function dayFields(d={}){return `<label>DAY 標題<input name="day" required value="${esc(d.day||'DAY '+(state.itinerary.length+1))}"></label><label>日期<input name="date" value="${esc(d.date||'')}"></label><label>主題<input name="title" required value="${esc(d.title||'')}"></label><label>簡介<input name="summary" value="${esc(d.summary||'')}"></label><label>行程（每行：時間｜地點｜類型）<textarea name="items" rows="8">${esc((d.items||[]).map(x=>x.join('｜')).join('\n'))}</textarea></label><button class="pill primary" type="submit">儲存</button>`}
function openDayForm(index=null){const d=index===null?{}:state.itinerary[index];document.getElementById('formTitle').textContent=index===null?'新增一天':'編輯行程';const form=document.getElementById('dynamicForm');form.innerHTML=dayFields(d);form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);const obj={day:fd.get('day').trim(),date:fd.get('date').trim(),title:fd.get('title').trim(),summary:fd.get('summary').trim(),items:fd.get('items').split(/\n+/).map(v=>v.trim()).filter(Boolean).map(v=>{const p=v.split(/[｜|]/).map(s=>s.trim());return[p[0]||'',p[1]||'',p[2]||'']})};index===null?state.itinerary.push(obj):state.itinerary[index]=obj;save();renderPlan();closeModal('formModal');toast('行程已儲存')};openModal('formModal')}
document.getElementById('addDayBtn').addEventListener('click',()=>openDayForm());
document.getElementById('cleanPlanBtn').addEventListener('click',()=>{document.getElementById('cleanPlan').innerHTML=state.itinerary.map(d=>`<div class="clean-day"><h3>${esc(d.day)}｜${esc(d.title)}</h3>${d.items.map(x=>`<div class="clean-stop"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div>`).join('');openModal('cleanModal')});

function renderPhrases(){const cats=['全部',...new Set(DATA.phrases.map(x=>x[0]))];document.getElementById('categoryChips').innerHTML=cats.map(c=>`<button class="chip ${c===currentCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');const q=document.getElementById('phraseSearch').value.toLowerCase();const list=DATA.phrases.map((x,i)=>({x,i})).filter(({x})=>(currentCategory==='全部'||x[0]===currentCategory)&&(!q||x.join(' ').toLowerCase().includes(q)));document.getElementById('phraseList').innerHTML=list.map(({x,i})=>`<article class="card"><div class="kr">${esc(x[1])}</div><div class="roman">${esc(x[2])}</div><div class="zh">${esc(x[3])}</div><span class="tag">${esc(x[0])}</span><div class="actions"><button class="btn primary voice-action" data-text="${esc(x[1])}" data-rate="0.88">🔊 發音</button><button class="btn voice-action" data-text="${esc(x[1])}" data-rate="0.58">🐢 慢速</button><button class="btn enlarge" data-index="${i}">🔍 放大</button><button class="btn favorite" data-index="${i}">${state.favorites.includes(i)?'💖 已收藏':'🤍 收藏'}</button></div></article>`).join('')||'<div class="empty">找不到語句</div>';document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{currentCategory=b.dataset.cat;renderPhrases()}));document.querySelectorAll('.enlarge').forEach(b=>b.addEventListener('click',()=>showPhrase(Number(b.dataset.index))));document.querySelectorAll('.favorite').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.index);state.favorites=state.favorites.includes(i)?state.favorites.filter(v=>v!==i):[...state.favorites,i];save();renderPhrases()}))}
function showPhrase(i){const x=DATA.phrases[i];modalPhrase=x;modalKr.textContent=x[1];modalRoman.textContent=x[2];modalZh.textContent=x[3];openModal('phraseModal')}
document.getElementById('phraseSearch').addEventListener('input',renderPhrases);
document.getElementById('modalSpeak').addEventListener('click',()=>window.HanVoice.play(modalPhrase?.[1],.88));document.getElementById('modalSlow').addEventListener('click',()=>window.HanVoice.play(modalPhrase?.[1],.58));

function renderExpenses(){const totals={};state.expenses.forEach(x=>totals[x.currency]=(totals[x.currency]||0)+Number(x.amount));expenseSummary.innerHTML=Object.entries(totals).map(([c,n])=>`<div class="summary"><span class="muted">${c} 合計</span><b>${n.toLocaleString()}</b></div>`).join('')||'<div class="summary"><span class="muted">目前花費</span><b>0</b></div>';expenseList.innerHTML=[...state.expenses].reverse().map(x=>`<article class="card"><div class="record-head"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.date)}・${esc(x.category)}</div></div><div class="record-amount">${Number(x.amount).toLocaleString()} ${esc(x.currency)}</div></div><div class="actions"><button class="btn mini delete-expense" data-id="${x.id}">刪除</button></div></article>`).join('')||'<div class="empty">尚無花費紀錄</div>';document.querySelectorAll('.delete-expense').forEach(b=>b.addEventListener('click',()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.id);save();renderExpenses()}))}
function openExpense(){formTitle.textContent='新增花費';dynamicForm.innerHTML=`<label>日期<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>項目<input name="title" required placeholder="例如：晚餐"></label><label>分類<select name="category"><option>餐飲</option><option>交通</option><option>購物</option><option>住宿</option><option>門票</option><option>其他</option></select></label><label>金額<input name="amount" required type="number" inputmode="decimal"></label><label>幣別<select name="currency"><option>KRW</option><option>TWD</option><option>USD</option><option>JPY</option></select></label><button class="pill primary">儲存</button>`;dynamicForm.onsubmit=e=>{e.preventDefault();const f=new FormData(dynamicForm);state.expenses.push({id:Date.now().toString(36),date:f.get('date'),title:f.get('title'),category:f.get('category'),amount:Number(f.get('amount')),currency:f.get('currency')});save();renderExpenses();closeModal('formModal');toast('花費已儲存')};openModal('formModal')}
addExpenseBtn.addEventListener('click',openExpense);

const rates={TWD:1,KRW:42.5,USD:1/30.8,JPY:1/0.205};function updateFx(){rates.KRW=Number(krwPerTwd.value)||42.5;state.krwPerTwd=rates.KRW;save();const a=Number(fxAmount.value)||0,from=fxFrom.value,to=fxTo.value;const twd=a/rates[from],out=twd*rates[to];fxResult.textContent=`${out.toLocaleString(undefined,{maximumFractionDigits:2})} ${to}`}
[fxAmount,fxFrom,fxTo,krwPerTwd].forEach(el=>el.addEventListener('input',updateFx));swapFx.addEventListener('click',()=>{[fxFrom.value,fxTo.value]=[fxTo.value,fxFrom.value];updateFx()});krwPerTwd.value=state.krwPerTwd||42.5;
function renderSOS(){sosList.innerHTML=DATA.sos.map((x,i)=>`<article class="card sos-card"><h3>${esc(x.title)}</h3><div class="kr">${esc(x.kr)}</div><div class="roman">${esc(x.roman)}</div><div class="zh">${esc(x.zh)}</div><div class="actions"><button class="btn primary voice-action" data-text="${esc(x.kr)}" data-rate="0.84">🔊 播放</button><button class="btn sos-enlarge" data-index="${i}">🔍 放大</button></div></article>`).join('');document.querySelectorAll('.sos-enlarge').forEach(b=>b.addEventListener('click',()=>{const x=DATA.sos[Number(b.dataset.index)];modalPhrase=['',x.kr,x.roman,x.zh];modalKr.textContent=x.kr;modalRoman.textContent=x.roman;modalZh.textContent=x.zh;openModal('phraseModal')}))}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=7001').catch(()=>{}));
renderPlan();renderPhrases();renderExpenses();renderSOS();updateFx();
